<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<createOrder xmlns="http://www.webex.com/blis/1.0/custom">
			<orderInstance>
				<Order>
					<OrderStatus>New</OrderStatus>
					<OrderID>${orderId}</OrderID>
					<CustomerAttributeID>${customerAttributeId}</CustomerAttributeID>
					<OrderFinApprove>OK</OrderFinApprove>
					<FinanceNotified/>
					<DefaultHDPartyID>${hdpartyId}</DefaultHDPartyID>
					<OPSNeeded4Creation>Yes</OPSNeeded4Creation>
					<SellType>No change</SellType>
					<NETUPO>Returning</NETUPO>
					<OrderEntityID>5</OrderEntityID>
					<Mon12BookingSellType>No change</Mon12BookingSellType>
					<SnapshotID/>
					<HDAddInfo accounttype="${accountType}" currency="${currency}" owner="${serviceProviderName}" orgname="${organizationName}" uponame="${upoName}">
						<getOrderAddInfoInCreateByAccIDResponse>
							<tuple>
								<old>
									<BLIS_ACCOUNT>
										<INVOICEDEFINITIONID>${invoicedefinitionId}</INVOICEDEFINITIONID>
										<HDPARTYID>${hdpartyId}</HDPARTYID>
										<ACCOUNTTYPE>${accountType}</ACCOUNTTYPE>
										<CURRENCYCODE>${currency}</CURRENCYCODE>
										<SERVICEPROVIDERID>${serviceProviderId}</SERVICEPROVIDERID>
										<SERVICEPROVIDERNAME>${serviceProviderName}</SERVICEPROVIDERNAME>
										<ORGNAME>${organizationName}</ORGNAME>
										<UPONAME null="true"/>
										<BILLDAY null="true"/>
										<SUBTYPE>${accountSubType}</SUBTYPE>
										<QCPCTSR null="true"/>
									</BLIS_ACCOUNT>
								</old>
							</tuple>
						</getOrderAddInfoInCreateByAccIDResponse>
					</HDAddInfo>
					<Customer>
						<CustomerForm>
							<STATUS>New</STATUS>
							<AccountName>${accountName}</AccountName>
							<OrgName>${organizationName}</OrgName>
							<ShowExchangeRate>1</ShowExchangeRate>
							<ExchangeRate>1.000</ExchangeRate>
							<ExchangeRateDate>${curDate}</ExchangeRateDate>
							<OrgID>${orgId}</OrgID>
							<AccountID>${accountId}</AccountID>
							<Comments/>
							<StrOpportunityID>4185680</StrOpportunityID>
							<orderformID/>
							<OrderTypeID>1</OrderTypeID>
							<OrderNumber>${orgId}-${accountId}-${orderId}</OrderNumber>
							<ChannelID>${channelId}</ChannelID>
							<Currency>USD</Currency>
							<OrderTotal>1</OrderTotal>
							<BookingDate/>
							<CompensationDate>${curDate}</CompensationDate>
							<NeedAdjustMent>true</NeedAdjustMent>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>sysdate</CREATIONDATE>
							<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
							<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
							<AccountManager1>${primarySRAgentId}</AccountManager1>
							<Team1>${primarySRAssignmentValue2}</Team1>
							<TeamLead1>-1</TeamLead1>
							<Percent1>${primarySRAssignmentValue1}</Percent1>
							<AccountManagerName1>${primarySRAgentName}</AccountManagerName1>                 
							<AccountManager4>${csmSRAgentId}</AccountManager4>
							<Team4>${csmSRAssignmentValue2}</Team4>
							<TeamLead4>-1</TeamLead4>
							<Percent4>${csmSRAssignmentValue1}</Percent4>
							<AccountManagerName4>${csmSRAgentName}</AccountManagerName4>                 
						</CustomerForm>
						<AgentAssignment>
							<AgentAssignmentID>${primarySRAgentAssignmentId}</AgentAssignmentID>
							<AgentID>${primarySRAgentId}</AgentID>
							<AssignmentTypeID>6</AssignmentTypeID>
							<AssignmentValue1>${primarySRAssignmentValue1}</AssignmentValue1>
							<AssignmentValue2>${primarySRAssignmentValue2}</AssignmentValue2>
							<AssignmentValue3>-1</AssignmentValue3>
							<ActionType>insert</ActionType>
						</AgentAssignment>
						<AgentAssignment>
							<AgentAssignmentID>${csmSRAgentAssignmentId}</AgentAssignmentID>
							<AgentID>${csmSRAgentId}</AgentID>
							<AssignmentTypeID>9</AssignmentTypeID>
							<AssignmentValue1>${csmSRAssignmentValue1}</AssignmentValue1>
							<AssignmentValue2>${csmSRAssignmentValue2}</AssignmentValue2>
							<AssignmentValue3>-1</AssignmentValue3>
							<ActionType>insert</ActionType>
						</AgentAssignment>
					</Customer>
					<ChannelPartnerSetting isDirty="false">
						<CommissionRate/>
					</ChannelPartnerSetting>
					<ReasonCodes>
					</ReasonCodes>
					<OrderOrderBooking>
						<ActionType>insert</ActionType>
						<BkgItem>
							<BookTypeID>215</BookTypeID>
							<BookValue>60.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>222</BookTypeID>
							<BookValue>0.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>210</BookTypeID>
							<BookValue>0.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>214</BookTypeID>
							<BookValue>0.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>203</BookTypeID>
							<BookValue>5884.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>218</BookTypeID>
							<BookValue>60.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>226</BookTypeID>
							<BookValue>259.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>223</BookTypeID>
							<BookValue>0.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>213</BookTypeID>
							<BookValue>95.598</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>219</BookTypeID>
							<BookValue>199.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>204</BookTypeID>
							<BookValue>5884.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>212</BookTypeID>
							<BookValue>95.598</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>225</BookTypeID>
							<BookValue>60.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>224</BookTypeID>
							<BookValue>199.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>220</BookTypeID>
							<BookValue>259.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>201</BookTypeID>
							<BookValue>259.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>221</BookTypeID>
							<BookValue>0.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>216</BookTypeID>
							<BookValue>199.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>211</BookTypeID>
							<BookValue>0.0</BookValue>
						</BkgItem>
						<BkgItem>
							<BookTypeID>202</BookTypeID>
							<BookValue>259.0</BookValue>
						</BkgItem>
					</OrderOrderBooking>
					<#include "order/orderServices.ftl">
				</Order>
				<#include "order/orderCSP.ftl">
			</orderInstance>
		</createOrder>
	</SOAP:Body>
</SOAP:Envelope>