					<Services type="page" isDeleted="false">
						<ORDERSERVICEID>${orderServiceId}</ORDERSERVICEID>
						<ActionType>insert</ActionType>
						<ServiceNumber>${orgId}-${accountId}-${orderId}</ServiceNumber>
						<ServiceID/>
						<ServiceName>MC</ServiceName>
						<oneTimeChargeTotal/>
						<monthlyChargeTotal/>
						<SubscriptionType>Seats</SubscriptionType>
						<SubscriptionValue1>25.0</SubscriptionValue1>
						<SubscriptionValue2/>
						<SnapshotID/>
						<Terms>
							<TermsForm>
								<SubscriptionName>110984-212418-175516</SubscriptionName>
								<ContractSignDate>${curDate}</ContractSignDate>
								<ServiceStartDate>${serviceStartDate}</ServiceStartDate>
								<InitialTerm>${initialTerm}</InitialTerm>
								<RenewalTerm>${renewalTerm}</RenewalTerm>
								<BillDay/>
								<purposeTerm>Normal</purposeTerm>
								<InterestRate>${interestRate}</InterestRate>
								<SuspendDate>${suspendDate}</SuspendDate>
								<TerminatNoticeDate>${terminatNoticeDate}</TerminatNoticeDate>
								<TerminatDate>${terminatDate}</TerminatDate>
								<ExpSvrStartDate>${expSvrStartDate}</ExpSvrStartDate>
							</TermsForm>
						</Terms>
						<Provision>
							<ProvisionForm>
								<ProvisionTicket>
									<ActionType>insert</ActionType>
									<ProvisionTicketID>${blisProvisionticketId}</ProvisionTicketID>
									<SiteID>${blisSiteId}</SiteID>
									<OrderServiceID>${orderServiceId}</OrderServiceID>
									<CreatedBy>452</CreatedBy>
									<CreationDate>sysdate</CreationDate>
									<LastModifiedBy>452</LastModifiedBy>
									<LastModifiedDate>systime</LastModifiedDate>
									<TicketType>DefaultSite</TicketType>
									<Status>Active</Status>					
									<ServiceTag>MC Named Hosts</ServiceTag>
								</ProvisionTicket>
								<ProvisionSetting>
									<ProvisionTicketID>${blisProvisionticketId}</ProvisionTicketID>
									<Name/>
									<Language>English</Language>
									<WebExURL>${webexUrl}</WebExURL>
									<TimeZone>(GMT -08:00) PACIFIC TIME,USA &amp; CANADA</TimeZone>
									<BrandSite>www.claytoolwssite.com</BrandSite>
									<ActionType>insert</ActionType>
									<SettingType>Primary</SettingType>
									<ProvisionSettingID>${blisProvisionsettingId}</ProvisionSettingID>
									<Status>Active</Status>
									<CreatedBy>452</CreatedBy>
									<CreationDate>sysdate</CreationDate>
									<LastModifiedBy>452</LastModifiedBy>
									<LastModifiedDate>sysdate</LastModifiedDate>
								</ProvisionSetting>
								<ProvisionSite>
									<SiteID>${blisSiteId}</SiteID>
									<CreatedBy>452</CreatedBy>
									<CreationDate>sysdate</CreationDate>
									<LastModifiedBy>452</LastModifiedBy>
									<LastModifiedDate>sysdate</LastModifiedDate>
									<Status>Active</Status>
									<ActionType>insert</ActionType>
								</ProvisionSite>
							</ProvisionForm>
							<OrderContactList>
								<Contacts>
									<BLIS_CONTACT>
										<ActionType>insert</ActionType>
										<CONTACTID>${contactId}</CONTACTID>
										<ENTITYID>24</ENTITYID>
										<ENTITYKEYID/>
										<INDIVIDUALID>${implContactIndividualId}</INDIVIDUALID>
										<CONTACTTYPEID>4</CONTACTTYPEID>
										<DESCRIPTION/>
										<STATUS>Active</STATUS>
										<CREATEDBY>452</CREATEDBY>
										<CREATIONDATE/>
										<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
										<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
									</BLIS_CONTACT>
								</Contacts>
							</OrderContactList>
							<AgentTypes>
							</AgentTypes>
						</Provision>
						<#include "order/offerInstance.ftl">
						<OrderServiceBooking>
							<ActionType>insert</ActionType>
							<AdditionInfo serviceModelType="Seats" serviceModelValue1="25.0" serviceModelValue2=""/>
							<BkgItem>
								<BookTypeID>126</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>104</BookTypeID>
								<BookValue>5884.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>112</BookTypeID>
								<BookValue>95.598</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>113</BookTypeID>
								<BookValue>95.598</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>118</BookTypeID>
								<BookValue>60.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>129</BookTypeID>
								<BookValue>199.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>124</BookTypeID>
								<BookValue>259.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>116</BookTypeID>
								<BookValue>199.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>132</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>125</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>115</BookTypeID>
								<BookValue>60.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>111</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>122</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>131</BookTypeID>
								<BookValue>259.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>119</BookTypeID>
								<BookValue>199.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>114</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>127</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>130</BookTypeID>
								<BookValue>60.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>108</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>103</BookTypeID>
								<BookValue>5884.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>128</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>102</BookTypeID>
								<BookValue>259.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>133</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>110</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>120</BookTypeID>
								<BookValue>0.0</BookValue>
							</BkgItem>
							<BkgItem>
								<BookTypeID>101</BookTypeID>
								<BookValue>259.0</BookValue>
							</BkgItem>
						</OrderServiceBooking>
					</Services>