  <SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<createAccount xmlns="http://www.webex.com/blis/1.0/custom">
			<AccountInstance>
				<Account xmlns="">
					<Customer>
						<CustomerForm>
							<SubType>${subType}</SubType>
							<OrganizationName>${organizationName}</OrganizationName>
							<AccountName>${accountName}</AccountName>
							<PartnerAccount/>
							<Relationship>${relationship}</Relationship>
							<RelationshipType>${relationshipType}</RelationshipType>
							<PrimaryBusiness>Telco</PrimaryBusiness>
							<SupportBy>${supportBy}</SupportBy>
							<TrainingBy>${supportBy}</TrainingBy>
							<IsWelEmailByWebEx>${isWelEmailByWebEx}</IsWelEmailByWebEx>
							<IsOtherEmailByWebEx>${isWelEmailByWebEx}</IsOtherEmailByWebEx>
							<ServiceHostBy/>
							<ImplementBy>${implementBy}</ImplementBy>
							<BillingMethodID>1</BillingMethodID>
							<PaymentMethod>1</PaymentMethod>
							<BillFrequency>Monthly</BillFrequency>
							<BillPresentment>${billPresentment}</BillPresentment>
							<PaymentTerm>Net 30</PaymentTerm>
							<Currency>USD</Currency>
							<BegeoId/>
							<Isccareassignpp>0</Isccareassignpp>
							<IslinktoCCARASP>0</IslinktoCCARASP>
							<RPAccountId/>
							<RPAccountRelationshipId>3236</RPAccountRelationshipId>
						</CustomerForm>
						<AccountData>
							<AccountNumber>${organizationId}-${accountId}</AccountNumber>
							<InitialSalesID>452</InitialSalesID>
							<CustomerID>${customerId}</CustomerID>
							<OrganizationUnitID>${organizationId}</OrganizationUnitID>
							<ParentAccountID>${organizationId}</ParentAccountID>
							<BillingAccountID/>
							<ChannelID>1</ChannelID>
							<BillingMethodID/>
							<ActiveFrom/>
							<ActiveTo/>
							<BillDay/>
							<CreditHold/>
							<TaxCode/>
							<CSAgentID>1</CSAgentID>
							<OPAgentID/>
							<ReasonCodeID/>
							<LastBillSentDate/>
							<Status>Pending-order</Status>
							<CreatedBy>452</CreatedBy>
							<CreationDate>systime</CreationDate>
							<ModifiedBy>452</ModifiedBy>
							<ModifiedDate>systime</ModifiedDate>
							<BILLINGADDRESSID/>
							<MAINADDRESSID/>
							<TeamLOBTerritoryID/>
							<AccountID>${accountId}</AccountID>
							<AddressID>${accountAddressId}</AddressID>
							<ServicePortfolioID/>
							<ContractPortfolioID>${contractPortfolioId}</ContractPortfolioID>
							<InvoiceDefinitionID>${invoiceDefinitionId}</InvoiceDefinitionID>
							<PartnerAttributeID>${partnerAttributeId}</PartnerAttributeID>
							<ServiceProvider>WebEx AUD</ServiceProvider>
							<OriginFlag>CMS</OriginFlag>                                  
						</AccountData>
						<ActionType>insert</ActionType>
						<AccountType>${accountTypeStr}</AccountType>
						<PartnerID/>
						<CurrAuthUser>452</CurrAuthUser>
					</Customer>
					<Addresses>
						<BLIS_ADDRESS>
							<ActionType>insert</ActionType>
							<ADDRESSID>${billingAddressId}</ADDRESSID>
							<ADDRESS1>1234567</ADDRESS1>
							<ADDRESS2/>
							<COUNTRY>US</COUNTRY>
							<CITY>claytestorg111city</CITY>
							<COUNTY/>
							<STATE>AL</STATE>
							<PROVINCE/>
							<POSTALCODE>11122</POSTALCODE>
							<PHONE>444-333-2222</PHONE>
							<FAX/>
							<STATUS>Active</STATUS>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>sysdate</CREATIONDATE>
							<LASTMODIFIEDBY/>
							<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
							<NOTES/>
							<ENTITYID>3</ENTITYID>
							<ENTITYKEYID>${accountId}</ENTITYKEYID>
						</BLIS_ADDRESS>
						<BLIS_ADDRESS>
							<ActionType>insert</ActionType>
							<ADDRESSID>${shipToAddressId}</ADDRESSID>
							<ADDRESS1>333222</ADDRESS1>
							<ADDRESS2/>
							<COUNTRY>US</COUNTRY>
							<CITY>claytestorg111cityship</CITY>
							<COUNTY/>
							<STATE>MS</STATE>
							<PROVINCE/>
							<POSTALCODE>33333</POSTALCODE>
							<PHONE>444-333-7777</PHONE>
							<FAX/>
							<STATUS>Active</STATUS>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>sysdate</CREATIONDATE>
							<LASTMODIFIEDBY/>
							<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
							<NOTES/>
							<ENTITYID>3</ENTITYID>
							<ENTITYKEYID>${accountId}</ENTITYKEYID>
						</BLIS_ADDRESS>
					</Addresses>
					<AddressTypes>
						<BLIS_ADDRESSREFERENCE>
							<ActionType>insert</ActionType>
							<ADDRESSREFERENCEID>${billingAddressRefId}</ADDRESSREFERENCEID>
							<ADDRESSTYPEID>10</ADDRESSTYPEID>
							<ADDRESSTYPE>Primary Billing</ADDRESSTYPE>
							<ADDRESSID>${billingAddressId}</ADDRESSID>
							<ENTITYID>3</ENTITYID>
							<ENTITYKEYID>${accountId}</ENTITYKEYID>
							<ENTITYNAME>ACCOUNT</ENTITYNAME>
							<STATUS>Active</STATUS>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>systime</CREATIONDATE>
							<LASTMODIFIEDBY/>
							<LASTMODIFIEDDATE>systime</LASTMODIFIEDDATE>
						</BLIS_ADDRESSREFERENCE>
						<BLIS_ADDRESSREFERENCE>
							<ActionType>insert</ActionType>
							<ADDRESSREFERENCEID>${shipToAddressRefId}</ADDRESSREFERENCEID>
							<ADDRESSTYPEID>11</ADDRESSTYPEID>
							<ADDRESSTYPE>Ship-to</ADDRESSTYPE>
							<ADDRESSID>${shipToAddressId}</ADDRESSID>
							<ENTITYID>3</ENTITYID>
							<ENTITYKEYID>${accountId}</ENTITYKEYID>
							<ENTITYNAME>ACCOUNT</ENTITYNAME>
							<STATUS>Active</STATUS>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>systime</CREATIONDATE>
							<LASTMODIFIEDBY/>
							<LASTMODIFIEDDATE>systime</LASTMODIFIEDDATE>
						</BLIS_ADDRESSREFERENCE>
					</AddressTypes>
					<Contacts>
						<BLIS_CONTACT>
							<ActionType>insert</ActionType>
							<CONTACTID>${billindContactId}</CONTACTID>
							<ENTITYID>3</ENTITYID>
							<ENTITYKEYID>${accountId}</ENTITYKEYID>
							<INDIVIDUALID>${billindIvidualId}</INDIVIDUALID>
							<CONTACTTYPEID>30</CONTACTTYPEID>
							<DESCRIPTION/>
							<STATUS>Active</STATUS>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>sysdate</CREATIONDATE>
							<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
							<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
						</BLIS_CONTACT>
						<BLIS_CONTACT>
							<ActionType>insert</ActionType>
							<CONTACTID>${businessContactId}</CONTACTID>
							<ENTITYID>3</ENTITYID>
							<ENTITYKEYID>${accountId}</ENTITYKEYID>
							<INDIVIDUALID>${businessIvidualId}</INDIVIDUALID>
							<CONTACTTYPEID>9</CONTACTTYPEID>
							<DESCRIPTION/>
							<STATUS>Active</STATUS>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>sysdate</CREATIONDATE>
							<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
							<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
						</BLIS_CONTACT>
						<#if subType="Partner VAR">
						<BLIS_CONTACT>
							<ActionType>insert</ActionType>
							<CONTACTID>${supportL1ContactId}</CONTACTID>
							<ENTITYID>3</ENTITYID>
							<ENTITYKEYID>${accountId}</ENTITYKEYID>
							<INDIVIDUALID>${supportL1IvidualId}</INDIVIDUALID>
							<CONTACTTYPEID>22</CONTACTTYPEID>
							<DESCRIPTION/>
							<STATUS>Active</STATUS>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>sysdate</CREATIONDATE>
							<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
							<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
						</BLIS_CONTACT>
						</#if>
					</Contacts>
					<Individuals>
					<#if subType="Partner VAR">
					<BLIS_INDIVIDUAL>
							<ActionType>insert</ActionType>
							<INDIVIDUALID>${supportL1IvidualId}</INDIVIDUALID>
							<FIRSTNAME>claytestorg111ls</FIRSTNAME>
							<LASTNAME>claytestorg111ls</LASTNAME>
							<WORKPHONENUMBER>444-333-2222ext.2385</WORKPHONENUMBER>
							<HOMEPHONENUMBER/>
							<CELLPHONENUMBER/>
							<EMAIL>claytestorg111ls@claytestorg111ls.com</EMAIL>
							<PAGERNUMBER/>
							<JOBTITLE/>
							<GROUPID/>
							<ORGANIZATIONUNITID/>
							<STATUS>Active</STATUS>
							<CREATEDBY>452</CREATEDBY>
							<CREATIONDATE>sysdate</CREATIONDATE>
							<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
							<LASTMODIFIEDDATE/>
							<INDIVIDUALTYPEID>1</INDIVIDUALTYPEID>
							<USERID/>
							<MIDDLENAME/>
							<EMAIL2/>
							<MAINADDRESSID/>
							<URL/>
							<ALLOWPROMOTION/>
							<ALLOWREFERENCE/>
							<REPORTSTO/>
							<DEPARTMENT>Sales</DEPARTMENT>
							<FAXNUMBER/>
							<MARKETINGPROJECT/>
							<REFERREDBY/>
							<ALLOWEMAIL>1</ALLOWEMAIL>
							<JOBFUNCTION>C - Level</JOBFUNCTION>
							<ENTITYID/>
							<ENTITYKEYID/>
							<INDIVIDUALADDRESS>
								<BLIS_ADDRESS>
									<ActionType>insert</ActionType>
									<ADDRESSID>${supportL1IndAddressId}</ADDRESSID>
									<ADDRESS1/>
									<ADDRESS2/>
									<COUNTRY>US</COUNTRY>
									<CITY/>
									<COUNTY/>
									<STATE>AL</STATE>
									<PROVINCE/>
									<POSTALCODE/>
									<PHONE/>
									<FAX/>
									<STATUS>Active</STATUS>
									<CREATEDBY>452</CREATEDBY>
									<CREATIONDATE>systime</CREATIONDATE>
									<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
									<LASTMODIFIEDDATE>systime</LASTMODIFIEDDATE>
									<NOTES/>
									<ENTITYID>9</ENTITYID>
									<ENTITYKEYID>${supportL1IvidualId}</ENTITYKEYID>
								</BLIS_ADDRESS>
							</INDIVIDUALADDRESS>
						</BLIS_INDIVIDUAL>
					</#if>
					</Individuals>
					<Agents>
						<BLIS_AGENTASSIGNMENT>
							<AgentID>231</AgentID>
							<TypeName>Current Owner</TypeName>
							<AssignmentValue1>0</AssignmentValue1>
							<AssignmentValue2>0</AssignmentValue2>
							<AgentAssignmentID>${currentOwnerSRId}</AgentAssignmentID>
							<EntityID>3</EntityID>
							<AssignmentTypeID>1</AssignmentTypeID>
							<ActionType>insert</ActionType>
							<Status>Active</Status>
						</BLIS_AGENTASSIGNMENT>
						<BLIS_AGENTASSIGNMENT>
							<AgentID>693</AgentID>
							<TypeName>Client Mgr-Primary</TypeName>
							<AssignmentValue1>0</AssignmentValue1>
							<AssignmentValue2>0</AssignmentValue2>
							<AgentAssignmentID>${csmSRId}</AgentAssignmentID>
							<EntityID>3</EntityID>
							<AssignmentTypeID>2</AssignmentTypeID>
							<ActionType>insert</ActionType>
							<Status>Active</Status>
						</BLIS_AGENTASSIGNMENT>
						<BLIS_AGENTASSIGNMENT>
							<AgentID>111003</AgentID>
							<TypeName>Sales Engineer</TypeName>
							<AssignmentValue1>0</AssignmentValue1>
							<AssignmentValue2>0</AssignmentValue2>
							<AgentAssignmentID>${salesEngineerId}</AgentAssignmentID>
							<EntityID>3</EntityID>
							<AssignmentTypeID>16</AssignmentTypeID>
							<ActionType>insert</ActionType>
							<Status>Active</Status>
						</BLIS_AGENTASSIGNMENT>
						<BLIS_AGENTASSIGNMENT>
							<AgentID>427</AgentID>
							<TypeName>Collections</TypeName>
							<AssignmentValue1>0</AssignmentValue1>
							<AssignmentValue2>0</AssignmentValue2>
							<AgentAssignmentID>${collectorId}</AgentAssignmentID>
							<EntityID>3</EntityID>
							<AssignmentTypeID>4</AssignmentTypeID>
							<ActionType>insert</ActionType>
							<Status>Active</Status>
						</BLIS_AGENTASSIGNMENT>
					</Agents>
					<PONumberData/>
					<Invoices>
						<Invoice>
							<ActionType>insert</ActionType>
							<data>
								<InvoiceInfo>
									<BLIS_INVOICE>
										<InvoiceID>${invoiceDefinitionId}</InvoiceID>
										<Name>claytestorgtoolwsa002</Name>
										<IsDefault>1</IsDefault>
										<AccountID>${accountId}</AccountID>
										<BillDay/>
										<BillingMethodID>1</BillingMethodID>
										<BillFrequency>Monthly</BillFrequency>
										<BillingAddressID/>
										<BillingContactID/>
										<PaymentMethodID>1</PaymentMethodID>
										<PaymentTerm>Net 30</PaymentTerm>
										<CurrencyCode>USD</CurrencyCode>
										<TaxCode>None</TaxCode>
										<TaxRate>0</TaxRate>
										<NotToExceed/>
										<GoodUntilDate/>
										<Description/>
										<Status>Pending</Status>
										<CreationDate>systime</CreationDate>
										<CreatedBy>452</CreatedBy>
										<LastModifiedBy/>
										<LastModifiedDate/>
										<Taxable/>
									</BLIS_INVOICE>
								</InvoiceInfo>
							</data>
							<TrackCodeList/>
							<AddressList>
								<AddressListItem>
									<AddressType>${contactType}</AddressType>
									<AddressID>${billingAddressId}</AddressID>
									<Street1>1234567</Street1>
									<City>claytestorg111city</City>
									<State/>
									<Country>US</Country>
									<Phone>444-333-2222</Phone>
								</AddressListItem>
							</AddressList>
							<ContactList>
								<ContactListItem>
									<ContactType>${contactType}</ContactType>
									<IndividualID>${billindIvidualId}</IndividualID>
									<Name>claytestorg111cb claytestorg111cb</Name>
									<Email>claytestorg111cb@claytestorg111cb.com</Email>
									<LastModifiedDate>sysdate</LastModifiedDate>
									<Phone>444-333-2222</Phone>
								</ContactListItem>
							</ContactList>
							<IDIndividuals/>
							<IDAddresses/>
						</Invoice>
					</Invoices>
					<#if subType="Partner Referral">
					<AgreeMent>
						<RevenueShare>
							<type>referral</type>
							<basis>collections</basis>
							<qcasrpst>60</qcasrpst>
							<qcaampst>40</qcaampst>
						</RevenueShare>
						<PERIOD1>
							<setup>40</setup>
							<from_month1>1</from_month1>
							<to_month1>12</to_month1>
							<coreServices>30</coreServices>
							<from_month2>1</from_month2>
							<to_month2>12</to_month2>
							<telephony>20</telephony>
							<from_month3>1</from_month3>
							<to_month3>12</to_month3>
							<PSO>10</PSO>
							<from_month4>1</from_month4>
							<to_month4>12</to_month4>
						</PERIOD1>
						<PERIOD2>
							<setup/>
							<from_month1/>
							<to_month1/>
							<coreServices/>
							<from_month2/>
							<to_month2/>
							<telephony/>
							<from_month3/>
							<to_month3/>
							<PSO/>
							<from_month4/>
							<to_month4/>
						</PERIOD2>
						<PERIOD3>
							<setup/>
							<from_month1/>
							<to_month1/>
							<coreServices/>
							<from_month2/>
							<to_month2/>
							<telephony/>
							<from_month3/>
							<to_month3/>
							<PSO/>
							<from_month4/>
							<to_month4/>
						</PERIOD3>
						<PERIOD4>
							<setup/>
							<from_month1/>
							<to_month1/>
							<coreServices/>
							<from_month2/>
							<to_month2/>
							<telephony/>
							<from_month3/>
							<to_month3/>
							<PSO/>
							<from_month4/>
							<to_month4/>
						</PERIOD4>
					</AgreeMent>
					</#if>
				</Account>
			</AccountInstance>
		</createAccount>
	</SOAP:Body>
</SOAP:Envelope>