<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<createOrganization xmlns="http://www.webex.com/blis/1.0/custom">
			<OrgInstance>
				<Organization xmlns="">
					<OrganizationForm>
						<OrgName>${organizationName}</OrgName>
						<TaxID/>
						<OpportunityName/>
						<Currency>USD</Currency>
						<Alias/>
						<DBNumber/>
						<LanguageID>1</LanguageID>
						<AnnualSalesDUNS/>
						<ParentOrganization ID="">
                        [none]
						</ParentOrganization>
						<EmployeeDUNS/>
						<TopParent ID=""/>  
						<DBNumberLastModifyDate/>
						<URL>www.tool-ws.com</URL>
						<SICCode/>      
						<Industry>Professional Services - Legal</Industry>
						<EmployeeNumber>123456</EmployeeNumber>
						<NamedAccount>1</NamedAccount>
						<AnnualRevenue>12345</AnnualRevenue>
						<MainAddressID>${mainAddressId}</MainAddressID>
						<ActionType>insert</ActionType>
						<OrgID>${orgId}</OrgID>
						<ParentID/>
						<UltimateParentID>${orgId}</UltimateParentID>
						<Status>Prospect</Status>
						<SysDBDate>${sysDate}</SysDBDate>
						<CreatedBy>452</CreatedBy>
						<LastModifiedBy>452</LastModifiedBy>
						<OriginFlag>CMS</OriginFlag>
						<Customer>
							<ActionType>insert</ActionType>
							<CustomerID>${customerId}</CustomerID>
							<CustomerType>Enterprise</CustomerType>
							<CustomerNumber>0</CustomerNumber>
							<ChannelID>1</ChannelID>
						</Customer>
						<OpportunityID xmlns="STROPPORTUNITYID"/>
						<StrOpportunityID/>
						<Individuals>
							<!--#assign individualList=user.individualList/-->
							<BLIS_INDIVIDUAL>
								<ActionType>insert</ActionType>
								<INDIVIDUALID>${individualId1}</INDIVIDUALID>
								<FIRSTNAME>claytestorg111cb</FIRSTNAME>
								<LASTNAME>claytestorg111cb</LASTNAME>
								<WORKPHONENUMBER>444-333-2222ext.2380</WORKPHONENUMBER>
								<HOMEPHONENUMBER/>
								<CELLPHONENUMBER/>
								<EMAIL>claytestorg111cb@claytestorg111cb.com</EMAIL>
								<PAGERNUMBER/>
								<JOBTITLE/>
								<GROUPID/>
								<ORGANIZATIONUNITID/>
								<STATUS>Active</STATUS>
								<CREATEDBY>452</CREATEDBY>
								<CREATIONDATE>sysdate</CREATIONDATE>
								<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
								<LASTMODIFIEDDATE/>
								<INDIVIDUALTYPEID>1</INDIVIDUALTYPEID>
								<USERID/>
								<MIDDLENAME/>
								<EMAIL2/>
								<MAINADDRESSID/>
								<URL/>
								<ALLOWPROMOTION/>
								<ALLOWREFERENCE/>
								<REPORTSTO/>
								<DEPARTMENT>Business Development / Channel</DEPARTMENT>
								<FAXNUMBER/>
								<MARKETINGPROJECT/>
								<REFERREDBY/>
								<ALLOWEMAIL>1</ALLOWEMAIL>
								<JOBFUNCTION>Administrative Assistant</JOBFUNCTION>
								<ENTITYID/>
								<ENTITYKEYID/>
								<INDIVIDUALADDRESS>
									<BLIS_ADDRESS>
										<ActionType>insert</ActionType>
										<ADDRESSID>${indAddressId1}</ADDRESSID>
										<ADDRESS1/>
										<ADDRESS2/>
										<COUNTRY>US</COUNTRY>
										<CITY/>
										<COUNTY/>
										<STATE>AL</STATE>
										<PROVINCE/>
										<POSTALCODE/>
										<PHONE/>
										<FAX/>
										<STATUS>Active</STATUS>
										<CREATEDBY>452</CREATEDBY>
										<CREATIONDATE>systime</CREATIONDATE>
										<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
										<LASTMODIFIEDDATE>systime</LASTMODIFIEDDATE>
										<NOTES/>
										<ENTITYID>9</ENTITYID>
										<ENTITYKEYID>${individualId1}</ENTITYKEYID>
									</BLIS_ADDRESS>
								</INDIVIDUALADDRESS>
							</BLIS_INDIVIDUAL>
							<BLIS_INDIVIDUAL>
								<ActionType>insert</ActionType>
								<INDIVIDUALID>${individualId2}</INDIVIDUALID>
								<FIRSTNAME>claytestorg111cu</FIRSTNAME>
								<LASTNAME>claytestorg111cu</LASTNAME>
								<WORKPHONENUMBER>444-333-2222ext.2381</WORKPHONENUMBER>
								<HOMEPHONENUMBER/>
								<CELLPHONENUMBER/>
								<EMAIL>claytestorg111cu@claytestorg111cu.com</EMAIL>
								<PAGERNUMBER/>
								<JOBTITLE/>
								<GROUPID/>
								<ORGANIZATIONUNITID/>
								<STATUS>Active</STATUS>
								<CREATEDBY>452</CREATEDBY>
								<CREATIONDATE>sysdate</CREATIONDATE>
								<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
								<LASTMODIFIEDDATE/>
								<INDIVIDUALTYPEID>1</INDIVIDUALTYPEID>
								<USERID/>
								<MIDDLENAME/>
								<EMAIL2/>
								<MAINADDRESSID/>
								<URL/>
								<ALLOWPROMOTION/>
								<ALLOWREFERENCE/>
								<REPORTSTO/>
								<DEPARTMENT>Customer Service &amp; Support</DEPARTMENT>
								<FAXNUMBER/>
								<MARKETINGPROJECT/>
								<REFERREDBY/>
								<ALLOWEMAIL>1</ALLOWEMAIL>
								<JOBFUNCTION>C - Level</JOBFUNCTION>
								<ENTITYID/>
								<ENTITYKEYID/>
								<INDIVIDUALADDRESS>
									<BLIS_ADDRESS>
										<ActionType>insert</ActionType>
										<ADDRESSID>${indAddressId2}</ADDRESSID>
										<ADDRESS1/>
										<ADDRESS2/>
										<COUNTRY>US</COUNTRY>
										<CITY/>
										<COUNTY/>
										<STATE>AL</STATE>
										<PROVINCE/>
										<POSTALCODE/>
										<PHONE/>
										<FAX/>
										<STATUS>Active</STATUS>
										<CREATEDBY>452</CREATEDBY>
										<CREATIONDATE>systime</CREATIONDATE>
										<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
										<LASTMODIFIEDDATE>systime</LASTMODIFIEDDATE>
										<NOTES/>
										<ENTITYID>9</ENTITYID>
										<ENTITYKEYID>${individualId2}</ENTITYKEYID>
									</BLIS_ADDRESS>
								</INDIVIDUALADDRESS>
							</BLIS_INDIVIDUAL>
						</Individuals>
						<Contacts>
							<!--#assign contactList=user.contactList/-->
							<BLIS_CONTACT>
								<ActionType>insert</ActionType>
								<CONTACTID>${contactId1}</CONTACTID>
								<ENTITYID>1</ENTITYID>
								<ENTITYKEYID>${orgId}</ENTITYKEYID>
								<INDIVIDUALID>${individualId1}</INDIVIDUALID>
								<CONTACTTYPEID>18</CONTACTTYPEID>
								<DESCRIPTION/>
								<STATUS>Active</STATUS>
								<CREATEDBY>452</CREATEDBY>
								<CREATIONDATE>sysdate</CREATIONDATE>
								<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
								<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
							</BLIS_CONTACT>
							<BLIS_CONTACT>
								<ActionType>insert</ActionType>
								<CONTACTID>${contactId2}</CONTACTID>
								<ENTITYID>1</ENTITYID>
								<ENTITYKEYID>${orgId}</ENTITYKEYID>
								<INDIVIDUALID>${individualId2}</INDIVIDUALID>
								<CONTACTTYPEID>17</CONTACTTYPEID>
								<DESCRIPTION/>
								<STATUS>Active</STATUS>
								<CREATEDBY>452</CREATEDBY>
								<CREATIONDATE>sysdate</CREATIONDATE>
								<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
								<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
							</BLIS_CONTACT>
						</Contacts>
						<Addresses>
							<!--#assign addressList=user.addressList/-->
							<BLIS_ADDRESS>
								<ActionType>insert</ActionType>
								<ADDRESSID>${mainAddressId}</ADDRESSID>
								<ADDRESS1>1234567</ADDRESS1>
								<ADDRESS2/>
								<COUNTRY>US</COUNTRY>
								<CITY>claytestorg111city</CITY>
								<COUNTY/>
								<STATE>AL</STATE>
								<PROVINCE/>
								<POSTALCODE>11122</POSTALCODE>
								<PHONE>444-333-2222</PHONE>
								<FAX/>
								<STATUS>Active</STATUS>
								<CREATEDBY>452</CREATEDBY>
								<CREATIONDATE>sysdate</CREATIONDATE>
								<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
								<LASTMODIFIEDDATE>sysdate</LASTMODIFIEDDATE>
								<NOTES/>
								<ENTITYID>1</ENTITYID>
								<ENTITYKEYID>${orgId}</ENTITYKEYID>
							</BLIS_ADDRESS>
						</Addresses>
						<AddressTypes>
							<!--#assign addressRefList=user.addressRefList/-->
							<BLIS_ADDRESSREFERENCE>
								<ActionType>insert</ActionType>
								<ADDRESSREFERENCEID>${addressRefId}</ADDRESSREFERENCEID>
								<ADDRESSTYPEID>3</ADDRESSTYPEID>
								<ADDRESSTYPE>Organization</ADDRESSTYPE>
								<ADDRESSID>${mainAddressId}</ADDRESSID>
								<ENTITYID>1</ENTITYID>
								<ENTITYKEYID>${orgId}</ENTITYKEYID>
								<ENTITYNAME>ORGANIZATIONUNIT</ENTITYNAME>
								<STATUS>Active</STATUS>
								<CREATEDBY>452</CREATEDBY>
								<CREATIONDATE>systime</CREATIONDATE>
								<LASTMODIFIEDBY>452</LASTMODIFIEDBY>
								<LASTMODIFIEDDATE>systime</LASTMODIFIEDDATE>
							</BLIS_ADDRESSREFERENCE>
						</AddressTypes>
						<SRAgentTypes>
							<SRAgentType>
								<ActionType>insert</ActionType>
								<Role>Initial SR</Role>
								<AgentAssignmentID>${agentAssignId1}</AgentAssignmentID>
								<EntityID>1</EntityID>
								<KeyID>${orgId}</KeyID>
								<AgentID>452</AgentID>
								<AssignmentTypeID>5</AssignmentTypeID>
								<AssignmentValue1>0</AssignmentValue1>
								<AssignmentValue2>0</AssignmentValue2>
								<Status>Active</Status>
								<CreatedBy>452</CreatedBy>
								<CreationDate>sysdate</CreationDate>
								<LastModifiedBy>452</LastModifiedBy>
								<LastModifiedDate>sysdate</LastModifiedDate>
							</SRAgentType>
							<SRAgentType>
								<ActionType>insert</ActionType>
								<Role>Current Owner</Role>
								<AgentAssignmentID>${agentAssignId2}</AgentAssignmentID>
								<EntityID>1</EntityID>
								<KeyID>${orgId}</KeyID>
								<AgentID>231</AgentID>
								<AssignmentTypeID>11</AssignmentTypeID>
								<AssignmentValue1>0</AssignmentValue1>
								<AssignmentValue2>0</AssignmentValue2>
								<Status>Active</Status>
								<CreatedBy>452</CreatedBy>
								<CreationDate>sysdate</CreationDate>
								<LastModifiedBy>452</LastModifiedBy>
								<LastModifiedDate>sysdate</LastModifiedDate>
							</SRAgentType>
							<SRAgentType>
								<ActionType>insert</ActionType>
								<Role>Sales Engineer</Role>
								<AgentAssignmentID>${agentAssignId3}</AgentAssignmentID>
								<EntityID>1</EntityID>
								<KeyID>${orgId}</KeyID>
								<AgentID>111003</AgentID>
								<AssignmentTypeID>13</AssignmentTypeID>
								<AssignmentValue1>0</AssignmentValue1>
								<AssignmentValue2>0</AssignmentValue2>
								<Status>Active</Status>
								<CreatedBy>452</CreatedBy>
								<CreationDate>sysdate</CreationDate>
								<LastModifiedBy>452</LastModifiedBy>
								<LastModifiedDate>sysdate</LastModifiedDate>
							</SRAgentType>
						</SRAgentTypes>
					</OrganizationForm>                  
				</Organization>
			</OrgInstance>
		</createOrganization>
	</SOAP:Body>
</SOAP:Envelope>
